# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blocks.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blocks.proto',
  package='bismuth',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x62locks.proto\x12\x07\x62ismuth\"\x90\x01\n\x02TX\x12\x11\n\ttimestamp\x18\x01 \x02(\x04\x12\x15\n\raddress_index\x18\x02 \x02(\r\x12\x17\n\x0frecipient_index\x18\x03 \x02(\r\x12\x0e\n\x06\x61mount\x18\x04 \x02(\x04\x12\x11\n\tsignature\x18\x05 \x02(\x0c\x12\x11\n\toperation\x18\x06 \x02(\t\x12\x11\n\topenfield\x18\x07 \x02(\t\"!\n\x05\x42lock\x12\x18\n\x03txs\x18\x01 \x03(\x0b\x32\x0b.bismuth.TX\"\x1a\n\x07\x41\x64\x64ress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x02(\t\"\x18\n\x06Pubkey\x12\x0e\n\x06pubkey\x18\x01 \x02(\x0c\"\x95\x01\n\x06\x42locks\x12\x12\n\nfrom_block\x18\x01 \x02(\r\x12\x10\n\x08to_block\x18\x02 \x02(\r\x12#\n\taddresses\x18\x03 \x03(\x0b\x32\x10.bismuth.Address\x12 \n\x07pubkeys\x18\x04 \x03(\x0b\x32\x0f.bismuth.Pubkey\x12\x1e\n\x06\x62locks\x18\x05 \x03(\x0b\x32\x0e.bismuth.Block')
)




_TX = _descriptor.Descriptor(
  name='TX',
  full_name='bismuth.TX',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='bismuth.TX.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_index', full_name='bismuth.TX.address_index', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recipient_index', full_name='bismuth.TX.recipient_index', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='bismuth.TX.amount', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='bismuth.TX.signature', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operation', full_name='bismuth.TX.operation', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='openfield', full_name='bismuth.TX.openfield', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=170,
)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='bismuth.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txs', full_name='bismuth.Block.txs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=205,
)


_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='bismuth.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='bismuth.Address.address', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=233,
)


_PUBKEY = _descriptor.Descriptor(
  name='Pubkey',
  full_name='bismuth.Pubkey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pubkey', full_name='bismuth.Pubkey.pubkey', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=259,
)


_BLOCKS = _descriptor.Descriptor(
  name='Blocks',
  full_name='bismuth.Blocks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_block', full_name='bismuth.Blocks.from_block', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_block', full_name='bismuth.Blocks.to_block', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addresses', full_name='bismuth.Blocks.addresses', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pubkeys', full_name='bismuth.Blocks.pubkeys', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blocks', full_name='bismuth.Blocks.blocks', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=411,
)

_BLOCK.fields_by_name['txs'].message_type = _TX
_BLOCKS.fields_by_name['addresses'].message_type = _ADDRESS
_BLOCKS.fields_by_name['pubkeys'].message_type = _PUBKEY
_BLOCKS.fields_by_name['blocks'].message_type = _BLOCK
DESCRIPTOR.message_types_by_name['TX'] = _TX
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['Pubkey'] = _PUBKEY
DESCRIPTOR.message_types_by_name['Blocks'] = _BLOCKS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TX = _reflection.GeneratedProtocolMessageType('TX', (_message.Message,), dict(
  DESCRIPTOR = _TX,
  __module__ = 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:bismuth.TX)
  ))
_sym_db.RegisterMessage(TX)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK,
  __module__ = 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:bismuth.Block)
  ))
_sym_db.RegisterMessage(Block)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESS,
  __module__ = 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:bismuth.Address)
  ))
_sym_db.RegisterMessage(Address)

Pubkey = _reflection.GeneratedProtocolMessageType('Pubkey', (_message.Message,), dict(
  DESCRIPTOR = _PUBKEY,
  __module__ = 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:bismuth.Pubkey)
  ))
_sym_db.RegisterMessage(Pubkey)

Blocks = _reflection.GeneratedProtocolMessageType('Blocks', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKS,
  __module__ = 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:bismuth.Blocks)
  ))
_sym_db.RegisterMessage(Blocks)


# @@protoc_insertion_point(module_scope)
